var dir_8cd2f2a0b2ca9f1ec5a02455b1d71457 =
[
    [ "filter", "dir_81728a0ef549d216d1fbb81527182896.html", "dir_81728a0ef549d216d1fbb81527182896" ],
    [ "anaglyph.cpp", "anaglyph_8cpp.html", null ],
    [ "anaglyph.h", "anaglyph_8h.html", null ],
    [ "colorconvert.cpp", "colorconvert_8cpp.html", null ],
    [ "colorconvert.h", "colorconvert_8h.html", null ],
    [ "correlation.cpp", "correlation_8cpp.html", null ],
    [ "correlation.h", "correlation_8h.html", null ],
    [ "filters.h", "filters_8h.html", null ],
    [ "fourier.cpp", "fourier_8cpp.html", null ],
    [ "fourier.h", "fourier_8h.html", null ],
    [ "imgprocess.cpp", "imgprocess_8cpp.html", null ],
    [ "imgprocess.h", "imgprocess_8h.html", null ],
    [ "imgtransform.cpp", "imgtransform_8cpp.html", null ],
    [ "imgtransform.h", "imgtransform_8h.html", null ],
    [ "linedetector.cpp", "linedetector_8cpp.html", null ],
    [ "linedetector.h", "linedetector_8h.html", null ],
    [ "morphologicaloper.cpp", "morphologicaloper_8cpp.html", null ],
    [ "morphologicaloper.h", "morphologicaloper_8h.html", null ],
    [ "shapedetection.cpp", "shapedetection_8cpp.html", null ],
    [ "shapedetection.h", "shapedetection_8h.html", "shapedetection_8h" ],
    [ "skeleton.cpp", "skeleton_8cpp.html", null ],
    [ "skeleton.h", "skeleton_8h.html", null ],
    [ "whitebalance.cpp", "whitebalance_8cpp.html", null ],
    [ "whitebalance.h", "whitebalance_8h.html", null ]
];