name: Generate Doxygen Docs

on:
  push:
    tags:
      - '*.*.*'  # Ejecutar el workflow cuando se empuje un tag que siga el patrón de versiones (X.X.X)
jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfmt-dev libopencv-dev libgdal-dev libproj-dev libboost-all-dev
        
    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y

    - name: Generate Doxyfile with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DWITH_OPENCV=ON \
                 -DWITH_GDAL=ON \
                 -DWITH_PROJ=ON \
                 -DBUILD_APPS=OFF \
                 -DBUILD_TEST=OFF \
                 -DBUILD_DOC=ON
        cmake --build . --target doc

    - name: Generate Doxygen documentation
      run: doxygen ./build/doc/Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
        destination_dir: ${{ github.ref_name }}
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        enable_jekyll: false
        disable_nojekyll: true
